### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [biggifraley/firehose#2]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by biggifraley** [comment]
Added and deployed!
Added: <meta name="viewport" content="width=device-width, initial-scale=1">
to head section of: application.html.erb
Information found at: http://www.w3schools.com/bootstrap/bootstrap_get_started.asp sub-section 2.
:-)

**Comment by biggifraley** [comment]
I guess I need to do something special here to show you the code that followed Added:
Let's try again
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by kenmazaika** [comment]
Thumbs up, Biggi.  Great job. :+1:
